services:
  db:
    image: mongo:8.0.11
    container_name: dekamond-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - dekamond-data:/data/db
      - dekamond-data:/var/log/mongodb
    command:
      - "--logpath"
      - "/var/log/mongodb/mongod.log"
  redis:
    image: redis:latest
    container_name: dekamond-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - dekamond-data:/data
  application:
    depends_on:
      - redis
      - db
    build:
      context: ./
      dockerfile: cmd/dockerfile
    container_name: dekamond-app
    environment:
      - DB_ADDRESS=mongodb://db:27017/
      - DB_USERNAME=admin_user
      - DB_PASSWORD=password
      - DB_NAME=dekamond
      - REDIS_ADDRESS=redis:6379
    ports:
      - "${APP_PORT:-9000}:${APP_PORT:-9000}"
volumes:
  dekamond-data:
