basePath: /
definitions:
  app.CheckRequest:
    properties:
      code:
        example: "123456"
        type: string
      phone:
        example: "09012345678"
        type: string
    type: object
  app.LoginRequest:
    properties:
      phone:
        example: "09012345678"
        type: string
    type: object
  app.SearchResponse:
    properties:
      code:
        type: integer
      result:
        items:
          $ref: '#/definitions/entity.User'
        type: array
    type: object
  entity.User:
    properties:
      id:
        type: string
      last_login:
        type: string
      phone:
        type: string
      register_at:
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: This an example OTP implementation
  title: dekamond example swagger API
  version: "0.1"
paths:
  /check:
    post:
      consumes:
      - application/json
      description: Accepts a phone number and an OTP code and return JWT token if
        they are valid
      parameters:
      - description: valid phone number and code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.CheckRequest'
      produces:
      - text/plain
      responses:
        "200":
          description: JWT containing user ID
          schema:
            type: string
      tags:
      - login
  /login:
    post:
      consumes:
      - application/json
      description: Accepts a phone number and create an OTP code if the phone number
        is valid and no OTP code is currently valid that number.
      parameters:
      - description: valid phone number as string
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.LoginRequest'
      responses:
        "201":
          description: No Content
  /search:
    get:
      description: Retrieve users
      parameters:
      - description: A valid phone number for searching a specific user.
        example: "09012345678"
        in: query
        name: phone
        type: string
      - description: A date range to search for users who registered within that period
          in YYYY-MM-DD format, separated by a comma.
        example: 2024-01-01,2025-10-12
        in: query
        name: register
        type: string
      - description: The page number of the results. Default is 1. Negative numbers
          and zero are treated as 1.
        in: query
        name: page
        type: integer
      - description: The number of items per page. Default is 10. Negative numbers
          and zero are treated as 1.
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.SearchResponse'
      tags:
      - user
swagger: "2.0"
