basePath: /
definitions:
  app.APIResponse:
    properties:
      code:
        type: integer
      result: {}
    type: object
  app.CheckRequest:
    properties:
      code:
        example: "123456"
        type: string
      phone:
        example: "09012345678"
        type: string
    type: object
  app.LoginRequest:
    properties:
      phone:
        example: "09012345678"
        type: string
    type: object
host: localhost:9000
info:
  contact: {}
  description: This an example OTP implementation
  title: dekamond example swagger API
  version: "0.1"
paths:
  /check:
    post:
      consumes:
      - application/json
      description: accepts a phone number and an OTP code and return JWT token if
        they are valid
      parameters:
      - description: valid phone number and code
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.CheckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.APIResponse'
  /login:
    post:
      consumes:
      - application/json
      description: accepts a phone number and create a OTP code if phone number is
        valid and there is no valid code for that number
      parameters:
      - description: valid phone number as string
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/app.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.APIResponse'
swagger: "2.0"
